server:
  port: 9021

spring:
  application:
    name: nacos-feign-consumer-service
# Nacos config
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# Feign
feign:
  sentinel:
    enabled: true